apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: lubelogger
type: Opaque
stringData:
  POSTGRES_DB: lubelogger
  POSTGRES_USER: lubelogger
  # TODO: CHANGE PASSWORD, THIS IS IMPORTANT MY BROTHER IN CHRIST 
  POSTGRES_PASSWORD: change-me-later
  POSTGRES_CONNECTION: Host=postgres;Port=5432;Username=lubelogger;Password=change-me-later;Database=lubelogger;Pooling=true;Maximum Pool Size=40;Timeout=15;Command Timeout=60;
