apiVersion: v1
kind: ksops
metadata:
  name: postgres-auth
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: lubelogger
type: Opaque
# This is going to be populated by sops, so we don't need to put anything here.
# The values will be encrypted and stored in the secrets.yml file.
stringData: {}
---
apiVersion: v1
kind: ksops
metadata:
  name: lubelogger-bootstrap-auth
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: lubelogger
type: Opaqu
# This is going to be populated by sops, so we don't need to put anything here.
# The values will be encrypted and stored in the secrets.yml file.
stringData: {}


