### This file should not be published to the public repository, as it contains sensitive information ###
### It's published here only for demonstration purposes. Please change the passwords and secrets before using it in production. ###
apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: lubelogger
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: lubelogger
type: Opaque
stringData:
    POSTGRES_DB: lubelogger
    POSTGRES_USER: lubelogger
    POSTGRES_PASSWORD: change-me
    POSTGRES_CONNECTION: Host=postgres;Port=5432;Username=lubelogger;Password=change-me;Database=lubelogger;Pooling=true;Maximum Pool Size=40;Timeout=15;Command Timeout=60;
---
apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-bootstrap-auth
    namespace: lubelogger
    labels:
        app.kubernetes.io/name: lubelogger
        app.kubernetes.io/part-of: lubelogger
type: Opaque
stringData:
    LUBELOGGER_BOOTSTRAP_USERNAME: admin
    LUBELOGGER_BOOTSTRAP_PASSWORD: change-me-later
