apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Storage for lubelogger data
  name: lubelogger-data
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: shared-data
    app.kubernetes.io/part-of: lubelogger
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Storage for cryptographic keys used by lubelogger.
  name: lubelogger-keys
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: shared-keys
    app.kubernetes.io/part-of: lubelogger
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
