apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lubelogger
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: lubelogger
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
