apiVersion: v1
kind: Service
metadata:
  name: lubelogger
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: lubelogger
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: lubelogger
  ports:
    - name: http
      port: 80
      targetPort: http
