apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lubelogger
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/part-of: lubelogger
spec:
  ingressClassName: traefik
  rules:
    - host: cars.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lubelogger
                port:
                  number: 80
