apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lubelogger-app
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: lubelogger

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - lubelog.example.com
      secretName: lubelogger-tls

  rules:
    - host: lubelog.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lubelogger-app
                port:
                  number: 80
