apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lubelogger
  namespace: lubelogger
  labels:
    app.kubernetes.io/name: lubelogger
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: lubelogger
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lubelogger
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: lubelogger
