apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secrets.yaml
  - 04-shared-storage.yaml
  - 05-postgres-service.yaml
  - 06-postgres-statefulset.yaml
  - 07-lubelogger-deployment.yaml
  - 08-lubelogger-deployment-keda.yaml
  #- 08-lubelogger-events-deployment.yaml
  - 09-lubelogger-service.yaml
  - 10-lubelogger-ingress.yaml
  - 12-lubelogger-pdb.yaml
